py_test(
    name = "python2_test",
    srcs = ["test_for_python2.py"],
    main = "test_for_python2.py",
    python_version = "PY2",
)

py_test(
    name = "python3_test",
    srcs = ["test_for_python3.py"],
    main = "test_for_python3.py",
    python_version = "PY3",
)
